#!/usr/bin/env php

### BEGIN INIT INFO
# Provides: yiid
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and stop yiid
# Description: The simple daemon extension for the Yii 2 framework
### END INIT INFO

<?php
$_SERVER['argv'] = array_merge(
    array_slice($_SERVER['argv'], 0, 1),
    ['daemon/' . $_SERVER['argv'][1]],
    array_slice($_SERVER['argv'], 2)
);
require(__DIR__ . '/../../../yii');
